<?php

/**
 * @file
 * Module that integrates external OCR service with Islandora Background Process module.
 */

/**
 * Islandora module that performs OCR as a background process.
 */

// Instantiate the object that manages the background process so that
// it can be invoked in one of the hooks in islandora_background_process.module.
$IslandoraOcrBackgroundProcess = new IslandoraBprocessOcr();

/**
 * Implements hook_menu().
 */
function islandora_bprocess_ocr_menu() {
  $items = array();
  $items['admin/islandora/tools/bprocessocr'] = array(
    'title' => 'Islandora Background Process OCR Service',
    'description' => 'Configure Islandora Background Process OCR Service.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_bprocess_ocr_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'includes/admin.form.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

